imageTag: &imageTag replace_this
asa-manager:
  nameOverride: asa-manager
  deployment:
    image:
      tag: *imageTag
config:
  nameOverride: config
  deployment:
    image:
      tag: *imageTag
device-telemetry:
  nameOverride: device-telemetry
  deployment:
    image:
      tag: *imageTag
diagnostics:
  nameOverride: diagnostics
  deployment:
    image:
      tag: *imageTag
identity-gateway:
  nameOverride: identity-gateway
  deployment:
    image:
      tag: *imageTag
iothub-manager:
  nameOverride: iothub-manager
  deployment:
    image:
      tag: *imageTag
reverse-proxy:
  nameOverride: reverse-proxy
  service:
    port: 10080
  deployment:
    image:
      tag: *imageTag
    port:
      http: 10080
    probes:
      enabled: false
storage-adapter:
  nameOverride: storage-adapter
  deployment:
    image:
      tag: *imageTag
tenant-manager:
  nameOverride: tenant-manager
  deployment:
    image:
      tag: *imageTag
webui:
  nameOverride: webui
  service:
    port: 10080
  deployment:
    image:
      tag: *imageTag
    port:
      http: 10080
    probes:
      enabled: false
nginx-ingress:
  controller:
    nodeSelector:
      beta.kubernetes.io/os: linux
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/os: linux
