apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kyles-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: reverse-proxy
          servicePort: 10080
        path: /(.*)